from __future__ import annotations

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from .analyzer import analyze_repository
from .models import Analysis, AnalyzeRequest, AskRequest, AskResponse

app = FastAPI(title="AURA Engineering Intelligence API", version="0.1.0")
app.add_middleware(CORSMiddleware, allow_origins=["http://localhost:3000"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"])


@app.get("/v1/health")
def health() -> dict[str, str]:
    return {"status": "ok", "service": "aura-api", "version": "0.1.0"}


@app.post("/v1/analyze", response_model=Analysis)
def analyze(request: AnalyzeRequest) -> Analysis:
    try:
        return analyze_repository(request.repository, request.max_files, request.max_file_bytes)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.post("/v1/ask", response_model=AskResponse)
def ask(request: AskRequest) -> AskResponse:
    # The model provider is intentionally isolated. This deterministic response makes
    # the endpoint useful in local development without requiring an API key.
    evidence = ["No model provider configured; response generated by the local safety fallback."]
    answer = ("AURA received your engineering question. Connect an LLM provider to enable "
              "repository-grounded reasoning; deterministic repository analysis is already available via /v1/analyze.")
    return AskResponse(answer=answer, evidence=evidence, provider="local-fallback")
